<?php


class Faker
{
    public static $firstNames = [
        'Deloise',
        'Love',
        'Ema',
        'Dagmar',
        'Tomi',
        'Shamika',
        'Raylene',
        'Parthenia',
        'Jacques',
        'Katrice',
        'Tyrell',
        'Darren',
        'Maryetta',
        'Marilynn',
        'Georgeanna',
        'Andera',
        'Erik',
        'Fredrick',
        'Hipolito',
        'Damian',
        'Joane',
        'Lyndsay',
        'Brain',
        'Leonie',
        'Robin',
        'Tomiko',
        'Corazon',
        'Tad',
        'Jutta',
        'Glennie',
        'Hye',
        'Rene',
        'Ceola',
        'Aracely',
        'Lenora',
        'Karly',
        'Hilaria',
        'Lahoma',
        'Emerita',
        'Kristine',
        'Willian',
        'Gloria',
        'Lulu',
        'Breana',
        'Coletta',
        'Ocie',
        'Kiley',
        'Lyman',
        'Nakia',
        'Gale',
        'Tawna',
        'Queenie',
        'Kenneth',
        'Rachal',
        'Paula',
        'Manuel',
        'Eustolia',
        'Louvenia',
        'Leigha',
        'Chae',
        'Janie',
        'Keri',
        'Shelli',
        'Jamila',
        'Audrea',
        'Devora',
        'Nathalie',
        'Heather',
        'Gerardo',
        'Yelena',
        'Ruby',
        'Byron',
        'Merlyn',
        'Tonda',
        'Cleora',
        'Ted',
        'Saul',
        'Kenna',
        'Virgilio',
        'Belinda',
        'Felisha',
        'Ute',
        'Guadalupe',
        'Philomena',
        'Edgardo',
        'Frankie',
        'Twila',
        'Aleen',
        'Cinderella',
        'Mindy',
        'Aretha',
        'Argentina',
        'Carmelia',
        'Cathryn',
        'Clarita',
        'Enda',
        'Neomi',
        'Denna',
        'Nolan',
        'Eugenie',
        'Hang',
        'Johannes',
        'Gladys',
        'Beula',
        'Lila',
        'Roderick',
        'Eric',
        'Cari',
        'Man',
        'Lesha',
        'Marian',
        'Wallace',
        'Shari',
        'Evelyn',
        'Janina',
        'Remona',
        'Max',
        'Angella',
        'Gisela',
        'Walter',
        'Daniell',
        'Valery',
        'Cliff',
        'Assunta',
        'Kanisha',
        'Katherine',
        'Charlsie',
        'Lashonda',
        'Johnsie',
        'Casandra',
        'Margarett',
        'Alia',
        'Arla',
        'Ivonne',
        'Monserrate',
        'Dwana',
        'Madeline',
        'Malena',
        'Ana',
        'Kali',
        'Portia',
        'Mattie',
        'Lynell',
        'Lauretta',
        'Britney',
        'Amal',
        'Camellia',
        'Hector',
        'Adele',
        'Michelina',
        'Georgiana',
        'Steve',
        'Rocco',
        'Petronila',
        'Victor',
        'Alisa',
        'Harry',
        'Charisse',
        'France',
        'Vernell',
        'Lekisha',
        'Eun',
        'Woodrow',
        'Arnold',
        'Rafael',
        'Adelaida',
        'Orlando',
        'Magaly',
        'Dorine',
        'Billie',
        'Florencia',
        'Lin',
        'Contessa',
        'Tatiana',
        'Orval',
        'Carmel',
        'Maryland',
        'Ruthe',
        'Carlie',
        'Adan',
        'Van',
        'Katheleen',
        'Nima',
        'Leisha',
        'Daphne',
        'Renate',
        'Xuan',
        'Edra',
        'Marlana',
        'Jennefer',
        'Steven',
        'Maisie',
        'Ja',
        'Imelda',
        'Treva',
        'Chere',
        'Krystyna',
        'Ona',
        'Dinorah',
        'Tamica',
    ];

    public static $lastNames = [
        'Aarons',
        'Abelson',
        'Aceto',
        'Ahn',
        'Albrecht',
        'Alfred',
        'Allie',
        'Amerine',
        'Ammon',
        'Anaya',
        'Angles',
        'Appelbaum',
        'Ardon',
        'Arias',
        'Auclair',
        'Bank',
        'Barfoot',
        'Beighley',
        'Beringer',
        'Bermejo',
        'Bernat',
        'Beumer',
        'Bigger',
        'Billingsley',
        'Bjornstad',
        'Blohm',
        'Bohan',
        'Boisvert',
        'Bondi',
        'Boss',
        'Bracamonte',
        'Brar',
        'Breault',
        'Brinkley',
        'Bruno',
        'Brunton',
        'Brzozowski',
        'Burrows',
        'Buse',
        'Caffee',
        'Carter',
        'Cartier',
        'Cassella',
        'Cazarez',
        'Christen',
        'Coffee',
        'Compos',
        'Constable',
        'Conyer',
        'Corbin',
        'Cordle',
        'Costillo',
        'Coulombe',
        'Councill',
        'Crabill',
        'Crepeau',
        'Daigle',
        'Dibiase',
        'Dildine',
        'Donalson',
        'Dorn',
        'Drone',
        'Drum',
        'Dry',
        'Dunnigan',
        'Durling',
        'Eady',
        'Eble',
        'Eck',
        'Ehlers',
        'Eller',
        'Ellingson',
        'Elmore',
        'Emmett',
        'Eslinger',
        'Ester',
        'Ewen',
        'Factor',
        'Farrelly',
        'Fawcett',
        'Fearn',
        'Files',
        'Fillion',
        'Fils',
        'Fimbres',
        'Flamm',
        'Fleagle',
        'Fleeman',
        'Fong',
        'Frierson',
        'Funari',
        'Funk',
        'Gaskell',
        'Gayer',
        'Geist',
        'Gerner',
        'Gibney',
        'Gieseke',
        'Gillette',
        'Gipe',
        'Glynn',
        'Golder',
        'Guizar',
        'Hallford',
        'Halsey',
        'Handel',
        'Haney',
        'Hersey',
        'Hessling',
        'Hesson',
        'Hibbitts',
        'Hobart',
        'Hora',
        'Hundt',
        'Hunley',
        'Ingrassia',
        'Jeffreys',
        'Jen',
        'Jorgennsen',
        'Josey',
        'Judy',
        'Justis',
        'Kite',
        'Klapp',
        'Kleve',
        'Lajeunesse',
        'Lamar',
        'Lamberth',
        'Laxton',
        'Leatherman',
        'Leiva',
        'Limones',
        'Lomeli',
        'Lovern',
        'Lueders',
        'Magallanes',
        'Magby',
        'Manderscheid',
        'Manners',
        'Marcello',
        'Marcus',
        'Maroney',
        'Marotz',
        'Massi',
        'Matthies',
        'Mcardle',
        'Mccasland',
        'Mccrady',
        'Mcgilvery',
        'Mcmorris',
        'Mcnitt',
        'Mcquillen',
        'Mejias',
        'Merino',
        'Midgette',
        'Molder',
        'Moline',
        'Montesino',
        'Motter',
        'Moy',
        'Muszynski',
        'Neil',
        'Niemann',
        'Niemiec',
        'Niswander',
        'Noe',
        'Okamura',
        'Overson',
        'Padgett',
        'Palin',
        'Panter',
        'Pecoraro',
        'Pero',
        'Perugini',
        'Peskin',
        'Pettiway',
        'Pfarr',
        'Piller',
        'Poche',
        'Principe',
        'Prosperie',
        'Rahim',
        'Raines',
        'Rance',
        'Reiber',
        'Rimes',
        'Ripley',
        'Riter',
        'Rivett',
        'Robinett',
        'Romig',
        'Rosso',
        'Roush',
        'Rulison',
        'Ruple',
        'Sabatini',
        'Schlegel',
        'Schramm',
        'Seth',
        'Sgro',

    ];

    public static $companyNames = [
        'Air Safety Inc',
        'Anytime Air Support Inc',
        'AtoZ Co Ltd',
        'Avery Software Co',
        'Calm Sailing Inc',
        'Chandler Logistics Inc',
        'Cloud Cover Trust',
        'Coolview Net Ltd',
        'Cumberland Trails Inc',
        'Davenport Investing',
        'DD Furniture Inc',
        'Dirt Mining Ltd',
        'Draft Diversified Energy Inc',
        'EEE Endowments LTD',
        'Gifted Holdings AG',
        'Hammer Group Inc',
        'Hollywood Diner Ltd',
        'Income Free Investing LP',
        'J.K.M. Corp (HA)',
        'JJ Resources Inc',
        'Jungle Systems Inc',
        'Kaos Trading Ltd',
        'King Software Inc',
        'Kings Royalty Trust',
        'Max Holdings Ltd',
        'Nelson Inc',
        'Nimble Technologies Inc',
        'NW Capital Corp',
        'Overhead & Underfoot Ltd.',
        'P Piper & Sons',
        'Powell Funding',
        'Pullman Cart Company',
        'Riviera Hotels',
        'Rubble Group Inc',
        'S Cane Sweeteners Ltd',
        'Sea Region Inc',
        'Slender Broadband Inc',
        'Smallville Resources Inc',
        'Smith & Sons',
        'South Sea Plumbing Products',
        'Spend Thrift Inc',
        'Start Over Trust',
        'Sunyvale Reporting Ltd',
        'SuperG Tech',
        'T-Squared Techs',
        'Tortoise Corp',
        'Tri-State Medical Corp',
        'Underwater Mining Inc.',
        'Waverly Trading House',
        'X-Sell Holdings',

    ];

    public static $phoneNumbers = [
        '(555) 089-2406',
        '(250) 103-0023',
        '(893) 917-0048',
        '(163) 547-3201',
        '(069) 459-8958',
        '(232) 373-4591',
        '(539) 543-7560',
        '(113) 454-0225',
        '(457) 422-5891',
        '(361) 274-8813',
        '(811) 833-6547',
        '(812) 056-3454',
        '(263) 829-2640',
        '(084) 618-9643',
        '(875) 670-6250',
        '(894) 567-8477',
        '(293) 822-6152',
        '(313) 147-5198',
        '(032) 049-7517',
        '(620) 347-8815',
        '(180) 701-1606',
        '(451) 344-2056',
        '(130) 207-3227',
        '(367) 744-0621',
        '(676) 100-6273',
        '(744) 075-7542',
        '(874) 708-1212',
        '(559) 537-7972',
        '(633) 675-5469',
        '(723) 156-0503',
        '(880) 872-3881',
        '(223) 029-4029',
        '(361) 575-8932',
        '(276) 391-8687',
        '(970) 970-7433',
        '(857) 909-2236',
        '(083) 843-8362',
        '(407) 916-1389',
        '(704) 715-0424',
        '(659) 867-7620',
        '(541) 447-5124',
        '(632) 442-0051',
        '(094) 158-0575',
        '(589) 685-0571',
        '(440) 255-3199',
        '(806) 130-2861',
        '(603) 995-6451',
        '(603) 183-0316',
        '(108) 624-5252',
        '(243) 265-4805',

    ];

    public static $countries = [
        'USA', 'DE', 'UA'
    ];

    public static $states = [
        'CA', 'NY', 'WY'
    ];

    public static $cities = [
        'Denver',
        'Los Angeles',
        'Kansas City',
        'Sunnyvale',
        'Santa Fe',
        'San Francisco',
        'Santa Monica',
        'Salt Lake City',
        'San Mateo',
        'San Jose',
        'Cupertino',
        'Persistance',
        'Alabama',
        'St. Petersburg',
        'Ohio',
    ];

    public static $streets = [
        '111 Silicon Valley Road',
        '345 Sugar Blvd.',
        '321 University Ave.',
        '777 West Filmore Ln',
        '48920 San Carlos Ave',
        '1715 Scott Dr',
        '123 Anywhere Street',
        '9 IBM Path',
        '67321 West Siam St.',
        '999 Baker Way',

    ];

    public static $postalCodes = [
        234567,23456,56788,234567,234567,0101010

    ];


}
